# Generated by Django 4.1.1 on 2024-11-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_listitem_item_desc_listitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='tag_color',
        ),
        migrations.AlterField(
            model_name='listitem',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=6),
        ),
    ]
