# Generated by Django 4.1.1 on 2024-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_listitem_tag_color_alter_listitem_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateitem',
            name='tag_color',
        ),
        migrations.AddField(
            model_name='templateitem',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=6),
        ),
    ]
